### ISSUE TITLE
Gallery Submission Feedback

### ISSUE THREAD

**Issue by delsonting** [przemoo83/gtm-intercom-widget-template#1]
Template approved, a few recommendations:

- Uri Encode data.widgetID using encodeUriComponent on line 281 of template.tpl file. Best practice is to Uri Encode in addition to field validation.
  injectScript('https://widget.intercom.io/widget/'+data.widgetId, onLoadedScript, onScriptError, 'Intercom');

- data.gtmOnSuccess or data.gtmOnFailure should be called exactly once per tag. This can be a bit tricky with async callbacks such as injectScript. A common approach is to keep track of successful calls and make sure that all calls completed successfully before returning data.gtmOnSuccess otherwise return data.gtmOnFailure 

- Line 26 of template.tpl:  Messanger -> Messenger

**Comment by przemoo83** [comment]
Thank a lot. Much appreciated :) changes done as suggested.
